title: El Arte del Cracking
description: Reverse Engineering y más
google_analytics:

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: Davidc96
  instagram:
  linkedin: david-cuadrado-gomez-60183013a/
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

include: ['_pages']